name: CI tests
run-name: ${{ github.actor }} CI tests
on:
  push:
    branches: [ $default-branch ]

  pull_request:
    branches: [ $default-branch ]

  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: nixos/nix

    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: "Tests"
        run: nix --extra-experimental-features 'nix-command flakes' run .#test
